########################## 
# CONFIGURATION FILE FOR VARIABLES 
# USED ACROSS THE PROJECT 
##########################


##########################  PIPELINE  ########################## 
# Pipeline flags for what processes to perform on the data
pipeline:
  # What  to read
  in:
    # Input
    inp: edges # med_rec or json currently. Future, the doid sample etc..
  # What to do with it
  trans:
    # Extract entities using metamap?
    metamap: False
    # Extract relations using reverb?
    reverb: False
    # Extract entities + relations through semrep?
    semrep: False
    # Transform edges, fetching concepts and other info?
    get_concepts_from_edges: True
  # What to do with the outcome
  out:
    # Create json output?
    json: True
    # Create .csv files for neo4j?
    csv: False
    # Create-update neo4 db?
    neo4j: False
########################## END PIPELINE ########################## 





##########################  INPUT ##########################
# Variables regarding loading
load:
  # Paths to binaries/files
  path:
    # Path to metamap
    metamap: /home/kostas/Downloads/public_mm_core/bin/metamap16
    # Path to reverb
    reverb: /media/kostas/DATA/GIT/reverb/core/
    # Path to semrep
    semrep: /media/kostas/DATA/LLD/SEMREP/public_semrep/bin/
  # For medical records
  med_rec:
    # Path to medical record txt
    inp_path: /media/kostas/DATA/LLD/Papers/BioASQ/MARIOS_PROJECT/100-patients/AdmissionsDiagnosesCorePopulatedTable.txt
    # Medical record name of the column to read text from
    textfield: PrimaryDiagnosisDescription
    # Field separator
    sep: \t
    # Idfield
    idfield: AdmissionID
  # For json files
  json:
    # Path to json from harvester
    inp_path: /media/kostas/DATA/LLD/Papers/BioASQ/MARIOS_PROJECT/Tasos_Tests/Article_PMC_abstracts_ENRICHED.json
    # Outer field name for the json documents
    docfield: documents
    # Name of the field to read text from
    textfield: abstractText
    # Idfield
    idfield: pmid
    # Label field
    labelfield: title
  edges:
    # Path to edges file
    inp_path: /media/kostas/DATA/LLD/Papers/BioASQ/MARIOS_PROJECT/Tasos_Tests/Edges_DRUGBANK_2.json
    # Name of the field where edges are stored
    edge_field: relations
    # Currently [Entity, Article and any new one]
    # Type of the subject
    sub_type: Entity
    # Type of the object
    obj_type: Entity
    # Currently [UMLS for cuis, PMC or TEXT for articles, None for precomputed and whatever else for DRUGBANK,MSH etc]
    # Id_field of the subject
    sub_source: DRUGBANK
    # Id_field of the subject
    obj_source: SWISS_PROT
##########################  END INPUT ##########################



##########################  API KEYS ##########################
# Variables regarding apis
apis:
  # Biontology for mapping cuis to uris
  biont: 1dd5cfd3-3a7b-4d34-8254-242e72d2a12b
  # Umls ticket service
  umls: 5e3ab18f-17fa-43f6-9cb2-41cccacc4ad5
##########################  END API KEYS ##########################



##########################  NEO4j ##########################
# Neoj variables
neo4j:
  # DB url
  host: localhost
  # port
  port: 7474 
  # user name
  user: neo4j
  # password
  password: admin
##########################  END NEO4j ##########################



##########################  OUTPUT ##########################
# Output variables
out:
   # Resulting .json file before neo4j
  json:
    # Path
    out_path: /media/kostas/DATA/LLD/Papers/BioASQ/MARIOS_PROJECT/Tasos_Tests/Edges_DRUG_ENRICHED2.json
    # Output json outer field name for the documents
    json_doc_field: relations
    # Output json text field for each document
    json_text_field: text
    # Output Idfield
    json_id_field: id
    # Output Label field
    json_label_field: title
    # Sentence Prefix
    sent_prefix: abstract
  # Resulting .json file before neo4j
  csv:
    # Path
    out_path: /media/kostas/DATA/LLD/Papers/BioASQ/MARIOS_PROJECT/out
  # Resulting .json file before neo4j
  neo4j:
    # Just for printing! Change the Neo4j field variables, not this!
    out_path: localhost:7474
##########################  END OUTPUT ##########################



